// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A review enhancement AI agent.
 *
 * - enhanceReview - A function that handles the review enhancement process.
 * - EnhanceReviewInput - The input type for the enhanceReview function.
 * - EnhanceReviewOutput - The return type for the enhanceReview function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EnhanceReviewInputSchema = z.object({
  reviewText: z
    .string()
    .describe('The text of the perfume review to be enhanced.'),
  communityFeedback: z
    .string()
    .describe('Community feedback on the perfume review.'),
});
export type EnhanceReviewInput = z.infer<typeof EnhanceReviewInputSchema>;

const EnhanceReviewOutputSchema = z.object({
  enhancedReview: z
    .string()
    .describe('The enhanced perfume review with improved clarity and completeness.'),
});
export type EnhanceReviewOutput = z.infer<typeof EnhanceReviewOutputSchema>;

export async function enhanceReview(input: EnhanceReviewInput): Promise<EnhanceReviewOutput> {
  return enhanceReviewFlow(input);
}

const prompt = ai.definePrompt({
  name: 'enhanceReviewPrompt',
  input: {schema: EnhanceReviewInputSchema},
  output: {schema: EnhanceReviewOutputSchema},
  prompt: `You are an AI expert in perfume review enhancement. Based on the community feedback, improve the clarity and completeness of the perfume review.

Perfume Review:
{{reviewText}}

Community Feedback:
{{communityFeedback}}

Enhanced Perfume Review:`,
});

const enhanceReviewFlow = ai.defineFlow(
  {
    name: 'enhanceReviewFlow',
    inputSchema: EnhanceReviewInputSchema,
    outputSchema: EnhanceReviewOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
